name = "RustCall"
uuid = "7ac5b1a4-9e37-4f0e-9aa3-3305a66bfb1c"
version = "0.1.0"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
RustToolChain = "e9dc52e2-edb8-4742-9783-5e542d30dbb5"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
BenchmarkTools = "1.6.3"
LLVM = "9"
RustToolChain = "0.1.1"
julia = "1.12"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
benchmark = ["BenchmarkTools"]
test = ["Test"]
